/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppMonitoringRouteImport } from './routes/app.monitoring'
import { Route as AppMapperRouteImport } from './routes/app.mapper'
import { Route as AppConnectorsRouteImport } from './routes/app.connectors'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as OauthZohoCallbackRouteImport } from './routes/oauth.zoho.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppMapperRoute = AppMapperRouteImport.update({
  id: '/mapper',
  path: '/mapper',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const OauthZohoCallbackRoute = OauthZohoCallbackRouteImport.update({
  id: '/oauth/zoho/callback',
  path: '/oauth/zoho/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/connectors': typeof AppConnectorsRoute
  '/app/mapper': typeof AppMapperRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/oauth/zoho/callback': typeof OauthZohoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/connectors': typeof AppConnectorsRoute
  '/app/mapper': typeof AppMapperRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/app': typeof AppIndexRoute
  '/oauth/zoho/callback': typeof OauthZohoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/billing': typeof AppBillingRoute
  '/app/connectors': typeof AppConnectorsRoute
  '/app/mapper': typeof AppMapperRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/oauth/zoho/callback': typeof OauthZohoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/billing'
    | '/app/connectors'
    | '/app/mapper'
    | '/app/monitoring'
    | '/app/workflows'
    | '/oauth/callback'
    | '/app/'
    | '/oauth/zoho/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/billing'
    | '/app/connectors'
    | '/app/mapper'
    | '/app/monitoring'
    | '/app/workflows'
    | '/oauth/callback'
    | '/app'
    | '/oauth/zoho/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/billing'
    | '/app/connectors'
    | '/app/mapper'
    | '/app/monitoring'
    | '/app/workflows'
    | '/oauth/callback'
    | '/app/'
    | '/oauth/zoho/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthZohoCallbackRoute: typeof OauthZohoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapper': {
      id: '/app/mapper'
      path: '/mapper'
      fullPath: '/app/mapper'
      preLoaderRoute: typeof AppMapperRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connectors': {
      id: '/app/connectors'
      path: '/connectors'
      fullPath: '/app/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/zoho/callback': {
      id: '/oauth/zoho/callback'
      path: '/oauth/zoho/callback'
      fullPath: '/oauth/zoho/callback'
      preLoaderRoute: typeof OauthZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBillingRoute: typeof AppBillingRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppMapperRoute: typeof AppMapperRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBillingRoute: AppBillingRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppMapperRoute: AppMapperRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthZohoCallbackRoute: OauthZohoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
